server:
 port: 8091
spring:
 application:
  name: microservice-users

 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

custom:
 security:
  jwt:
   key: ${JWT_KEY}
   issuer: ${JWT_ISSUER}
   ttMillis: ${JWT_TT_MILLIS}

